# A workflow to build and push a Docker image to Amazon ECR
name: Build and push image to ECR

on:
  push:
    branches: ["main"]

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 514246414247.dkr.ecr.us-east-1.amazonaws.com


      - name: Build Docker image
        run: |
          docker build -t nedrone:v4 .

      - name: Tag Docker image
        run: |
          docker tag nedrone:v4 514246414247.dkr.ecr.us-east-1.amazonaws.com/nedrone:v4

      - name: Push Docker image
        run: |
          docker push 514246414247.dkr.ecr.us-east-1.amazonaws.com/nedrone:v4

  deploy:
    runs-on: ubuntu-latest 
    needs: build-push
    steps:
      - name: Check my ssh-key
        run: |
          echo "${{ secrets.SSH_KEY }}" > ssh-key.pem
          chmod 600 ssh-key.pem
          cat ssh-key.pem

          

         # ssh -o StrictHostKeyChecking=no -i ssh-key.pem ubuntu@44.221.67.195 "hostnamectl"

      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to EC2 instance
        run: |
          ssh -o StrictHostKeyChecking=no -i ssh-key.pem ubuntu@34.231.243.228 "docker pull 514246414247.dkr.ecr.us-east-1.amazonaws.com/nedrone:v4"

          ssh -o StrictHostKeyChecking=no -i ssh-key.pem ubuntu@34.231.243.228 "docker run -d -p80:80 514246414247.dkr.ecr.us-east-1.amazonaws.com/nedrone:v4"