# A workflow to build and p[ush a Docker image to Amazon ECR
name: Build and push image to ECR

on:
  # Runs on pushes targeting the main branch
  push:
    branches: ["main"]

  
jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
        - name: checkout code
          uses: actions/checkout@v3

        # Configure AWS credentials

        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: ${{ secrets.AWS_REGION }}

        # Log in to Amazon ECR
        - name: Login to Amazon ECR
          id: login-ecr
          uses: aws-actions/amazon-ecr-login@v2
      
            # Build and push Docker image to ECR
        - name: Build and push image to ECR
          run:
            docker build -t nedrone .
            docker tag nedrone:v1 514246414247.dkr.ecr.us-east-1.amazonaws.com/nedrone:v1
            docker push 514246414247.dkr.ecr.us-east-1.amazonaws.com/nedrone:v1
            